{% set name = "badger-opt" %}
{% set version = "1.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 29fe02d2ea034e9c2db29552e4f26b5c5979be1170230287fc1514ecd56cceb0

build:
  number: 0
  noarch: python
  entry_points:
    - badger = badger.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - pyqt
    - pyqtgraph
    - qdarkstyle
    - coolname
    - pillow
    - requests
    - xopt

test:
  imports:
    - badger
  commands:
    - badger
  requires:
    - pip

about:
  home: https://github.com/slaclab/Badger
  summary: Badger optimizer
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wenatuhs
