{% set name = "badger-opt" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/badger-opt-{{ version }}.tar.gz
  sha256: 74c268eafeb3d771795bde53c330f482391dac9a6542412b51804631f6369fe6

build:
  number: 0
  noarch: python
  entry_points:
    - badger = badger.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - coolname
    - pandas
    - pillow
    - pyqt
    - pyqtgraph
    - python >=3.6
    - pyyaml
    - qdarkstyle

test:
  imports:
    - badger
    - badger.actions
  commands:
    - pip check
    - badger --help
  requires:
    - pip

about:
  home: https://github.com/SLAC-ML/Badger
  summary: Core of the Badger optimizer
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wenatuhs
