{% set name = "badger-opt" %}
{% set version = "1.3.3" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0f752d12e5a5543962eeba4ca2dbe238a58f0f5b2140dfbdf2444b813aa6fdfa

build:
  number: 0
  noarch: python
  entry_points:
    - badger = badger.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - pyqt
    - pyqtgraph
    - qdarkstyle
    - coolname
    - pillow
    - requests
    - xopt >=2.5.4

test:
  imports:
    - badger
  commands:
    - bash -c "mkdir -p /home/conda/.config && echo 'y' | badger"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/xopt-org/Badger
  summary: Badger optimizer
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wenatuhs
    - pluflou
