{% set name = "badger-opt" %}
{% set version = "1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/badger-opt-{{ version }}.tar.gz
  sha256: 9e904ea613c0e2f69fb86afd243db1dee6d252f08b1705c32d1b3dbf6a2b6b6f

build:
  number: 0
  noarch: python
  entry_points:
    - badger = badger.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - coolname
    - pandas
    - pillow
    - pyqt
    - pyqtgraph
    - python >=3.9
    - pyyaml
    - qdarkstyle
    - requests
    - tqdm
    - xopt

test:
  imports:
    - badger
  requires:
    - pytest
    - pytest-qt
    - pytest-mock
  commands:
    - pytest --pyargs badger

about:
  home: https://github.com/slaclab/Badger
  summary: Badger optimizer
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wenatuhs
